name: build

on: [push]

jobs:

  server:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}

    - name: Set up java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 11
        java-package: jre

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./sbt server/compile

    - name: Build binary (GraalVM native-image)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./sbt server/nativeImage

    - name: Deploy server
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:login
        heroku container:push --app bittorrent-server web
        heroku container:release --app bittorrent-server web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}