name: build

on: [ push ]

jobs:

  server:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}

      - name: Set up java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt server/stage

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/torrentdam/server:${{ github.sha }}
